### ISSUE TITLE
Wallee's python-sdk 4.2.0 not installable on Windows

### ISSUE THREAD

**Issue by pierrejean-coudert** [wallee-payment/python-sdk#10]
pip install fails:
```
Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\pierr\AppData\Local\Temp\pip-resolver-oj4jea2g\wallee\setup.py", line 6, in <module>
            long_description = fh.read()
          File "c:\users\pierr\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3960: character maps to <undefined>
```
The culprit is here:
https://github.com/wallee-payment/python-sdk/blob/882199a3dc3df2b27001343de0fceda3242c273e/setup.py#L5

It could be fixed with:
```python
 with open("README.md", "r",  encoding="utf8") as fh: 
```

Temporary workaround:

define `PYTHONUTF8=1`

**Comment by AmandaWallee** [comment]
Hi,
thanks for reporting this issue. 
Our development will investigate this bug.

**Comment by AmandaWallee** [comment]
Hi 

Our development has investigated the bug. 

Released Python SDK - https://github.com/wallee-payment/python-sdk/releases/tag/5.0.0

## BugFix
- Explicitly specifies *UTF-8* encoding to ensure proper character handling.
- For read operations, if the entity is not found, return *None* instead of an entity with no attributes.
- Refactored unit tests.

Have a good day.

**Comment by pierrejean-coudert** [comment]
Thanks !
